package com.project.base_v1.enums;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    REGISTER,
    IMPORT_STUDENT_REGISTRY,
    UPDATE_STUDENT_REGISTRY,
    ACTIVATE_STUDENT,
    DEACTIVATE_STUDENT,
    CREATE_REGISTRATION,
    CANCEL_REGISTRATION,
    APPROVE_REGISTRATION,
    REJECT_REGISTRATION,
    CREATE_ASSIGNMENT,
    END_ASSIGNMENT,
    CREATE_CONTRACT,
    ACTIVATE_CONTRACT,
    RENEW_CONTRACT,
    TERMINATE_CONTRACT,
    EXPIRE_CONTRACT,
    CREATE_METER,
    RECORD_METER_READING,
    CREATE_TARIFF,
    ISSUE_INVOICE,
    RECORD_PAYMENT
}
