package com.project.base_v1.enums;

public enum Permission {
    ACCOUNT_READ,
    ACCOUNT_MANAGE,
    ROLE_PERMISSION_MANAGE,
    USER_READ,
    USER_MANAGE,
    PROFILE_READ,
    PROFILE_WRITE,
    FACILITY_READ,
    FACILITY_MANAGE,
    REGISTRATION_MANAGE,
    ASSIGNMENT_MANAGE,
    CONTRACT_MANAGE,
    BILLING_MANAGE,
    OPERATIONS_MANAGE,
    REPORT_READ,
    AUDIT_READ,
    SYSTEM_CONFIG_MANAGE
}
